.TH "FreezingState" 3 "Mon Sep 23 2019" "StatePatternDoxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FreezingState
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBState\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrun\fP (\fBStateMachine\fP *stateMachine)"
.br
.ti -1c
.RI "virtual void \fBready\fP (\fBStateMachine\fP *stateMachine)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for StatePatternDoxygen from the source code\&.
