.TH "md__d_1_git__state_pattern__state_pattern__r_e_a_d_m_e" 3 "Mon Sep 23 2019" "StatePatternDoxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__d_1_git__state_pattern__state_pattern__r_e_a_d_m_e \- StatePattern 

.SH "General establishment"
.PP
.IP "1." 4
I'm looking for the way to use \fBState\fP Pattern without dynamic memory allocation\&. It's important for compliance with MISRA standard\&.
.IP "2." 4
\fBState\fP machine should be safe\&. It can't allow to change state accidentialy\&.
.PP
.SH "Program description"
.PP
The passes between states are only allowed on way shown on diagram\&.
.PP
 
